name:                dunai-gloss
version:             0.1.0
github:              "xayon40-12/dunai-gloss"
license:             BSD3
author:              "Nathan Touroux"
maintainer:          "touroux.nathan@gmail.com"
copyright:           "Copyright (c) 2021, Nathan Touroux"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  A Gloss interface for dunai.

  Please see the README on GitHub at <https://github.com/xayon40-12/dunai-gloss#readme>

dependencies:
- base >= 4.7 && < 5
- dunai
- mtl
- transformers
- gloss

library:
  source-dirs: src

executables:
  basic-circle:
    main:                BasicCircle.hs
    source-dirs:         examples/basic-circle
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dunai-gloss
